#Expyriment 0.9.0 (Python 2.7.15), .xpe-file, coding: cp1252
#date: Wed Jan 30 2019 15:45:03
#sha1: 195d6c
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: ('Windows', 'EDU-JBOOTH-MOB', '10', '10.0.17134', 'AMD64', 'Intel64 Family 6 Model 142 Stepping 9, GenuineIntel')
Time,Type,Event,Value,Detail,Detail2
10997,design,log,
#design: #exp: whole_number_to_position
#design: block_cnt,block_id,trial_cnt,trial_id
10997,design,logged,
10997,Experiment,started
11011,Stimulus,presented,1
11017,Stimulus,presented,1
11029,Stimulus,presented,1
11043,Stimulus,presented,2
11597,Stimulus,presented,2
11729,Stimulus,presented,2
12159,TextInput,entered,kk
12172,Stimulus,presented,2
12178,Stimulus,presented,2
12196,Stimulus,presented,2
12210,Stimulus,presented,3
12938,TextInput,entered,k
12940,stderr,received,'Traceback (most recent call last):'
12940,stderr,received,'  File "C:\\Users\\stemlab\\Documents\\GitHub\\tft\\whole_number_to_position.py", line 72, in <module>'
12941,stderr,received,'    num2pos.create_experiment_objects(exp_info)'
12941,stderr,received,'  File "C:\\Python27\\lib\\site-packages\\trajtrackerp\\num2pos\\_n2p_init.py", line 53, in create_experiment_objects'
12943,stderr,received,'    load_data_source(exp_info)'
12944,stderr,received,'  File "C:\\Python27\\lib\\site-packages\\trajtrackerp\\num2pos\\_n2p_init.py", line 245, in load_data_source'
12945,stderr,received,'    exp_info.trials, fieldnames = loader.load_file(ds)'
12945,stderr,received,'  File "C:\\Python27\\lib\\site-packages\\trajtracker\\io\\_CSVLoader.py", line 96, in load_file'
12946,stderr,received,'    row = self._transform_types(row, filename)'
12947,stderr,received,'  File "C:\\Python27\\lib\\site-packages\\trajtracker\\io\\_CSVLoader.py", line 157, in _transform_types'
12947,stderr,received,'    format(row[self.FLD_LINE_NUM], filename, e))'
12948,stderr,received,"trajtracker.BadFormatError: BadFormatError: Invalid CSV file format (line 47 in whole_number_to_position_2019.csv): invalid literal for int() with base 10: ''"
